### ISSUE TITLE
What is that script panel?

### ISSUE THREAD

**Issue by schroef** [alexander-ladygin/illustrator-scripts#2]
I was wondering which script panel that is in your previews?

**Comment by alexander-ladygin** [comment]
Hi,

LAScripts - http://ladygin.pro/products/lascripts/

**Comment by schroef** [comment]
Ah thanks Alexander for the link. Looks very useful!!!

**Comment by schroef** [comment]
Hi Alexander, been a while. Im busy with a script for Photoshop and got tired of going to the menu all the time so wanted to try out LAscripts.

Im trying to use ZXP installer but i get this error
```
Illustrator-scripts - scripts voor Adobe Illustrator  Ontwikkeling - Ladygin.pro.html
```
Cant i manually drop the unzipped zxp file in a folder?
I cant upgrade to higher photoshop due to my os, system is a but slower.

**Comment by schroef** [comment]
I installed the folder manually now in the CEP folder and panel seems to work properly.
```
/Users/romboutversluijs/Library/Application Support/Adobe/CEP/extensions/LAScripts_
```
I do get this message in the panel at the bottom, but scripts seem to run fine.
```
/Users/romboutversluijs/Library/Application Support/Adobe/CEP/extensions/LAScripts_
```

One thing i do see is that in the settings the "filtering options" doesnt seem to be doing anything. I get highlighting the files and folder should folder those files right? Because on closing main settings i still see other files.

PS i didnt see an option for this, but i like to be able to hide dot-files. On OSX we always get a lot of dot-files on USB drives. Im using scripts from a folder which has all my collected scripts
<img width="353" alt="Screen Shot 2020-01-12 at 15 14 22" src="https://user-images.githubusercontent.com/6923008/72224227-636c8900-354e-11ea-90f3-d38ed0563a98.png">

**Comment by schroef** [comment]
Sorry i had not read the page yet, i see the filtering does work. I just need to delete the added types. I thought i needed to highlight them. Perhaps some kind of toggle mechanism would be handier. Because say we want to use a different folder where we do want certain files to show. We would need re-add those types again.

What would be nice is that making them highlight would active them. All other are deactivated.
<img width="403" alt="Screen Shot 2020-01-12 at 15 21 53" src="https://user-images.githubusercontent.com/6923008/72224295-45ebef00-354f-11ea-93ae-0ed0170cab85.png">
