### ISSUE TITLE
Add new language?

### ISSUE THREAD

**Issue by VSPacheco** [alexander-ladygin/illustrator-scripts#20]
How to add a new language?
I edited the lines
......
names: {
                pt: {
                    oneLetter: [
                        'S',
                        'T',
                        'Q',
                        'Q',
                        'S',
                        'S',
                        'D'
                    ],
                    shortForm: [
                        'Seg',
                        'Ter',
                        'Qua',
                        'Qui',
                        'Sex',
                        'Sáb',
                        'Dom'
                    ],
                    fullWord: [
                        'Segunda',
                        'Terça',
                        'Quarta',
                        'Quinta',
                        'Sexta',
                        'Sábado',
                        'Domingo'
                    ],
                    weeks: {
                        oneLetter: 'S',
                        shortForm: 'Sem',
                        fullWord:  'Semana',
                    },
                    months: [
                        'Janeiro',
                        'Fevereiro',
                        'Março',
                        'Abril',
                        'Maio',
                        'Junho',
                        'Julho',
                        'Agosto',
                        'Setembro',
                        'Outubro',
                        'Novembro',
                        'Dezembro'
                    ]
                },
..........
var __lang = add('dropdownlist', undefined, '**Português**,Russian,Ukrainian,English,Deutsch,French,Spanish,Italian,Danish'.split(','));

**Comment by alexander-ladygin** [comment]
Added ;)
