### ISSUE TITLE
Fillinger script (Error 25: Expected: }. Line: 31)

### ISSUE THREAD

**Issue by lennydelmar** [alexander-ladygin/illustrator-scripts#29]
Have a notice from Illustarator 2022 (MacOS) when starting the script:
Error 25: Expected: }. 
Line: 31
-> <script type="application/json" id="client-env">{"locale":"en","featureFlags":["failbot_handle_non_errors","fix_react_title","geojson_azure_maps","image_metric_tracking","remove_react_base_styles","turbo_experiment_risky","use_scroll_restoration","sample_network_conn_type"]}</script>

Any solution in this?

**Comment by creold** [comment]
@lennydelmar You didn't download the script properly. Click on the Raw button and save the file. It will have a .txt extension, remove it to leave only .jsx

**Comment by lennydelmar** [comment]
Thanks for the solution. By the way it was downloaded with a proper extension. So I replace the existed file with a new one.
