### ISSUE TITLE
Uknown function getActiveArtboards

### ISSUE THREAD

**Issue by schroef** [alexander-ladygin/illustrator-scripts#4]
OSX 10.11.6
2018 cc
LAscripts 1.10

I was testing out the function for the artboards and noticed they have unknown functions.
This function for instance "getActiveArtboard()" I'm using 2018 cc, is this perhaps only for newer versions? I tried searching in the folder with all your scripts, the functions isn't anywhere but it is called quite a few times.

```
activeDocument.getActiveArtboard()
    .Width('500px', { anchor: 'center' })
    .Height('500px', { anchor: 'center' });
```

**Comment by alexander-ladygin** [comment]
Hi,

Most likely, the AI_PS_Library.js library is not included. Turn it on and everything should work. The latest version of the library is on github.

How to enable the library (but you can always load your code):
https://www.dropbox.com/s/f8wajsp7kr9jsyd/lascripts_libraries.mp4?dl=1
