### ISSUE TITLE
Error in the Code for Randomus.jsx

### ISSUE THREAD

**Issue by mkahl507** [alexander-ladygin/illustrator-scripts#5]
Hi there I am trying to use your cool randomus script and when I run the script I get an error in the code saying Error 23: & does not have a value. Line: 146

Was hoping to use this create some great patterns. 

If you can help that would be great. thanks.

**Comment by alexander-ladygin** [comment]
Hi, can you show the process of work, it just might be a lot of nuances?

**Comment by kiattiong** [comment]
Change , on line 23 to ; will solve the issue.

**Comment by Htoratsa** [comment]
@mkahl507 It seems you saved the webpage instead of the script (it happened to me also...). Open the script and check the content or download it again.

**Comment by mkahl507** [comment]
There was an error on line 23... instead of , it should be ;. I added this to my version and it worked beautifully. Thanks

**Comment by SAM-CP-20** [comment]
Hi there, I'm getting a similar error message. tried looking into editing the script using 'Sublime Text' but there is nothing on line 23... (total newbie when it comes to code I'm afraid!) 

<img width="549" alt="Screen Shot 2020-10-01 at 11 58 35" src="https://user-images.githubusercontent.com/72200477/94801949-b5a45180-03de-11eb-8436-8be11c7b8386.png">

**Comment by mkahl507** [comment]
Someone on the thread suggested a solution and that worked for me... I am
not exactly sure what it was at the moment. Let me see what if I can find
the script I have that is edited.. and send it to you.
